
package org.rifidi.edge.client.ale.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 09 14:35:36 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "DuplicateNameException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class DuplicateNameExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090209143536L;
    
    private org.rifidi.edge.client.ale.wsdl.ale.epcglobal.DuplicateNameException duplicateNameException;

    public DuplicateNameExceptionResponse() {
        super();
    }
    
    public DuplicateNameExceptionResponse(String message) {
        super(message);
    }
    
    public DuplicateNameExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateNameExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.ale.epcglobal.DuplicateNameException duplicateNameException) {
        super(message);
        this.duplicateNameException = duplicateNameException;
    }

    public DuplicateNameExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.ale.epcglobal.DuplicateNameException duplicateNameException, Throwable cause) {
        super(message, cause);
        this.duplicateNameException = duplicateNameException;
    }

    public org.rifidi.edge.client.ale.wsdl.ale.epcglobal.DuplicateNameException getFaultInfo() {
        return this.duplicateNameException;
    }
}
