
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.rifidi.edge.epcglobal.ale;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T14:01:05.543-05:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ALEService",
                      portName = "ALEServicePort",
                      targetNamespace = "urn:epcglobal:ale:wsdl:1",
                      wsdlLocation = "org/rifidi/edge/ale/xsd/EPCglobal-ale-1_1-ale.wsdl",
                      endpointInterface = "org.rifidi.edge.epcglobal.ale.ALEServicePortType")
                      
public class ALEServicePortImpl implements ALEServicePortType {

    private static final Logger LOG = Logger.getLogger(ALEServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#immediate(org.rifidi.edge.epcglobal.ale.Immediate  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.ECReports immediate(Immediate parms) throws ImplementationExceptionResponse , SecurityExceptionResponse , ECSpecValidationExceptionResponse    { 
        LOG.info("Executing operation immediate");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.ECReports _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ECSpecValidationExceptionResponse("ECSpecValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#getECSpecNames(org.rifidi.edge.epcglobal.ale.EmptyParms  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.ArrayOfString getECSpecNames(EmptyParms parms) throws ImplementationExceptionResponse , SecurityExceptionResponse    { 
        LOG.info("Executing operation getECSpecNames");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#undefine(org.rifidi.edge.epcglobal.ale.Undefine  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.VoidHolder undefine(Undefine parms) throws ImplementationExceptionResponse , NoSuchNameExceptionResponse , SecurityExceptionResponse    { 
        LOG.info("Executing operation undefine");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.VoidHolder _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#define(org.rifidi.edge.epcglobal.ale.Define  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.VoidHolder define(Define parms) throws ImplementationExceptionResponse , SecurityExceptionResponse , ECSpecValidationExceptionResponse , DuplicateNameExceptionResponse    { 
        LOG.info("Executing operation define");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.VoidHolder _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ECSpecValidationExceptionResponse("ECSpecValidationExceptionResponse...");
        //throw new DuplicateNameExceptionResponse("DuplicateNameExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#unsubscribe(org.rifidi.edge.epcglobal.ale.Unsubscribe  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.VoidHolder unsubscribe(Unsubscribe parms) throws ImplementationExceptionResponse , NoSuchSubscriberExceptionResponse , NoSuchNameExceptionResponse , SecurityExceptionResponse , InvalidURIExceptionResponse    { 
        LOG.info("Executing operation unsubscribe");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.VoidHolder _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchSubscriberExceptionResponse("NoSuchSubscriberExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InvalidURIExceptionResponse("InvalidURIExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#poll(org.rifidi.edge.epcglobal.ale.Poll  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.ECReports poll(Poll parms) throws ImplementationExceptionResponse , NoSuchNameExceptionResponse , SecurityExceptionResponse    { 
        LOG.info("Executing operation poll");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.ECReports _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#getSubscribers(org.rifidi.edge.epcglobal.ale.GetSubscribers  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.ArrayOfString getSubscribers(GetSubscribers parms) throws ImplementationExceptionResponse , NoSuchNameExceptionResponse , SecurityExceptionResponse    { 
        LOG.info("Executing operation getSubscribers");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.ArrayOfString _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#subscribe(org.rifidi.edge.epcglobal.ale.Subscribe  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.VoidHolder subscribe(Subscribe parms) throws ImplementationExceptionResponse , NoSuchNameExceptionResponse , SecurityExceptionResponse , InvalidURIExceptionResponse , DuplicateSubscriptionExceptionResponse    { 
        LOG.info("Executing operation subscribe");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.VoidHolder _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InvalidURIExceptionResponse("InvalidURIExceptionResponse...");
        //throw new DuplicateSubscriptionExceptionResponse("DuplicateSubscriptionExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#getECSpec(org.rifidi.edge.epcglobal.ale.GetECSpec  parms )*
     */
    public org.rifidi.edge.epcglobal.ale.ECSpec getECSpec(GetECSpec parms) throws ImplementationExceptionResponse , NoSuchNameExceptionResponse , SecurityExceptionResponse    { 
        LOG.info("Executing operation getECSpec");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.ale.ECSpec _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#getStandardVersion(org.rifidi.edge.epcglobal.ale.EmptyParms  parms )*
     */
    public java.lang.String getStandardVersion(EmptyParms parms) throws ImplementationExceptionResponse    { 
        LOG.info("Executing operation getStandardVersion");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.ale.ALEServicePortType#getVendorVersion(org.rifidi.edge.epcglobal.ale.EmptyParms  parms )*
     */
    public java.lang.String getVendorVersion(EmptyParms parms) throws ImplementationExceptionResponse    { 
        LOG.info("Executing operation getVendorVersion");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

}
