
package org.rifidi.edge.epcglobal.ale;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T14:01:05.528-05:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "NoSuchSubscriberException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class NoSuchSubscriberExceptionResponse extends Exception {
    
    private org.rifidi.edge.epcglobal.ale.NoSuchSubscriberException noSuchSubscriberException;

    public NoSuchSubscriberExceptionResponse() {
        super();
    }
    
    public NoSuchSubscriberExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchSubscriberExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSubscriberExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.NoSuchSubscriberException noSuchSubscriberException) {
        super(message);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public NoSuchSubscriberExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.NoSuchSubscriberException noSuchSubscriberException, Throwable cause) {
        super(message, cause);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public org.rifidi.edge.epcglobal.ale.NoSuchSubscriberException getFaultInfo() {
        return this.noSuchSubscriberException;
    }
}
