
package org.rifidi.edge.epcglobal.ale;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T14:01:05.512-05:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "SecurityException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class SecurityExceptionResponse extends Exception {
    
    private org.rifidi.edge.epcglobal.ale.SecurityException securityException;

    public SecurityExceptionResponse() {
        super();
    }
    
    public SecurityExceptionResponse(String message) {
        super(message);
    }
    
    public SecurityExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.SecurityException securityException) {
        super(message);
        this.securityException = securityException;
    }

    public SecurityExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.SecurityException securityException, Throwable cause) {
        super(message, cause);
        this.securityException = securityException;
    }

    public org.rifidi.edge.epcglobal.ale.SecurityException getFaultInfo() {
        return this.securityException;
    }
}
