
package org.rifidi.edge.client.ale.api.wsdl.ale.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Mar 02 15:00:47 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "DuplicateSubscriptionException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class DuplicateSubscriptionExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090302150047L;
    
    private org.rifidi.edge.client.ale.api.wsdl.ale.epcglobal.DuplicateSubscriptionException duplicateSubscriptionException;

    public DuplicateSubscriptionExceptionResponse() {
        super();
    }
    
    public DuplicateSubscriptionExceptionResponse(String message) {
        super(message);
    }
    
    public DuplicateSubscriptionExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public DuplicateSubscriptionExceptionResponse(String message, org.rifidi.edge.client.ale.api.wsdl.ale.epcglobal.DuplicateSubscriptionException duplicateSubscriptionException) {
        super(message);
        this.duplicateSubscriptionException = duplicateSubscriptionException;
    }

    public DuplicateSubscriptionExceptionResponse(String message, org.rifidi.edge.client.ale.api.wsdl.ale.epcglobal.DuplicateSubscriptionException duplicateSubscriptionException, Throwable cause) {
        super(message, cause);
        this.duplicateSubscriptionException = duplicateSubscriptionException;
    }

    public org.rifidi.edge.client.ale.api.wsdl.ale.epcglobal.DuplicateSubscriptionException getFaultInfo() {
        return this.duplicateSubscriptionException;
    }
}
