package org.rifidi.edge.core.exception.readerConnection;

import org.rifidi.edge.core.exception.RifidiException;

public class RifidiIllegalOperationException extends RifidiException {

	/**
	 * Autogenerated SerialVersionID
	 */
	private static final long serialVersionUID = 183170652719764201L;

	public RifidiIllegalOperationException() {
		super();
	}

	public RifidiIllegalOperationException(String message, Throwable cause) {
		super(message, cause);
	}

	public RifidiIllegalOperationException(String message) {
		super(message);
	}

	public RifidiIllegalOperationException(Throwable cause) {
		super(cause);
	}

}
