
package org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 09 14:59:11 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "ReaderLoopException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ReaderLoopExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090209145911L;
    
    private org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.ReaderLoopException readerLoopException;

    public ReaderLoopExceptionResponse() {
        super();
    }
    
    public ReaderLoopExceptionResponse(String message) {
        super(message);
    }
    
    public ReaderLoopExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ReaderLoopExceptionResponse(String message, org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.ReaderLoopException readerLoopException) {
        super(message);
        this.readerLoopException = readerLoopException;
    }

    public ReaderLoopExceptionResponse(String message, org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.ReaderLoopException readerLoopException, Throwable cause) {
        super(message, cause);
        this.readerLoopException = readerLoopException;
    }

    public org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.ReaderLoopException getFaultInfo() {
        return this.readerLoopException;
    }
}
