
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Mar 02 15:28:33 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "ALELRService",
                      portName = "ALELRServicePort",
                      targetNamespace = "urn:epcglobal:alelr:wsdl:1",
                      wsdlLocation = "file:EPCglobal-ale-1_1-alelr.wsdl",
                      endpointInterface = "org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType")
                      
public class ALELRServicePortTypeImpl implements ALELRServicePortType {

    private static final Logger LOG = Logger.getLogger(ALELRServicePortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#getLRSpec(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.GetLRSpec  parms )*
     */
    public org.rifidi.edge.client.ale.api.xsd.alelr.epcglobal.LRSpec getLRSpec(GetLRSpec parms) throws SecurityExceptionResponse , ImplementationExceptionResponse , NoSuchNameExceptionResponse    { 
        LOG.info("Executing operation getLRSpec");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.xsd.alelr.epcglobal.LRSpec _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#getStandardVersion(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.EmptyParms  parms )*
     */
    public java.lang.String getStandardVersion(EmptyParms parms) throws ImplementationExceptionResponse    { 
        LOG.info("Executing operation getStandardVersion");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#undefine(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.Undefine  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.UndefineResult undefine(Undefine parms) throws SecurityExceptionResponse , InUseExceptionResponse , ImplementationExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse    { 
        LOG.info("Executing operation undefine");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.UndefineResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#define(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.Define  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.DefineResult define(Define parms) throws SecurityExceptionResponse , ImplementationExceptionResponse , DuplicateNameExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation define");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.DefineResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new DuplicateNameExceptionResponse("DuplicateNameExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#setProperties(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.SetProperties  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.SetPropertiesResult setProperties(SetProperties parms) throws SecurityExceptionResponse , InUseExceptionResponse , ImplementationExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation setProperties");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.SetPropertiesResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#removeReaders(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.RemoveReaders  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.RemoveReadersResult removeReaders(RemoveReaders parms) throws NonCompositeReaderExceptionResponse , SecurityExceptionResponse , InUseExceptionResponse , ImplementationExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse    { 
        LOG.info("Executing operation removeReaders");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.RemoveReadersResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#addReaders(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.AddReaders  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.AddReadersResult addReaders(AddReaders parms) throws ReaderLoopExceptionResponse , NonCompositeReaderExceptionResponse , SecurityExceptionResponse , InUseExceptionResponse , ImplementationExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation addReaders");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.AddReadersResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
        //throw new NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#update(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.Update  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.UpdateResult update(Update parms) throws ReaderLoopExceptionResponse , SecurityExceptionResponse , InUseExceptionResponse , ImplementationExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation update");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.UpdateResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#setReaders(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.SetReaders  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.SetReadersResult setReaders(SetReaders parms) throws ReaderLoopExceptionResponse , NonCompositeReaderExceptionResponse , SecurityExceptionResponse , InUseExceptionResponse , ImplementationExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation setReaders");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.SetReadersResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
        //throw new NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#getVendorVersion(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.EmptyParms  parms )*
     */
    public java.lang.String getVendorVersion(EmptyParms parms) throws ImplementationExceptionResponse    { 
        LOG.info("Executing operation getVendorVersion");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#getLogicalReaderNames(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.EmptyParms  parms )*
     */
    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ArrayOfString getLogicalReaderNames(EmptyParms parms) throws SecurityExceptionResponse , ImplementationExceptionResponse    { 
        LOG.info("Executing operation getLogicalReaderNames");
        System.out.println(parms);
        try {
            org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ArrayOfString _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ALELRServicePortType#getPropertyValue(org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.GetPropertyValue  parms )*
     */
    public java.lang.String getPropertyValue(GetPropertyValue parms) throws SecurityExceptionResponse , ImplementationExceptionResponse , NoSuchNameExceptionResponse    { 
        LOG.info("Executing operation getPropertyValue");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
    }

}
