
package org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Mar 02 15:28:33 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "ImplementationException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ImplementationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090302152833L;
    
    private org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImplementationException implementationException;

    public ImplementationExceptionResponse() {
        super();
    }
    
    public ImplementationExceptionResponse(String message) {
        super(message);
    }
    
    public ImplementationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImplementationExceptionResponse(String message, org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImplementationException implementationException) {
        super(message);
        this.implementationException = implementationException;
    }

    public ImplementationExceptionResponse(String message, org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImplementationException implementationException, Throwable cause) {
        super(message, cause);
        this.implementationException = implementationException;
    }

    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImplementationException getFaultInfo() {
        return this.implementationException;
    }
}
