package org.rifidi.edge.core.adapter.dummyadapter;

public enum EDummyError {
	CONNECT, DISCONNECT, GET_NEXT_TAGS, SEND_CUSTOM_COMMAND,
	CONNECT_RUNTIME, DISCONNECT_RUNTIME, GET_NEXT_TAGS_RUNTIME, SEND_CUSTOM_COMMAND_RUNTIME,	
	SEND_CUSTOM_COMMAND2,
	NONE;
}
