
package org.rifidi.edge.epcglobal.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T10:17:43.084-05:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "ImmutableReaderException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ImmutableReaderExceptionResponse extends Exception {
    
    private org.rifidi.edge.epcglobal.alelr.ImmutableReaderException immutableReaderException;

    public ImmutableReaderExceptionResponse() {
        super();
    }
    
    public ImmutableReaderExceptionResponse(String message) {
        super(message);
    }
    
    public ImmutableReaderExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImmutableReaderExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ImmutableReaderException immutableReaderException) {
        super(message);
        this.immutableReaderException = immutableReaderException;
    }

    public ImmutableReaderExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ImmutableReaderException immutableReaderException, Throwable cause) {
        super(message, cause);
        this.immutableReaderException = immutableReaderException;
    }

    public org.rifidi.edge.epcglobal.alelr.ImmutableReaderException getFaultInfo() {
        return this.immutableReaderException;
    }
}
