
package org.rifidi.edge.epcglobal.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T10:17:43.105-05:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "ImplementationException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ImplementationExceptionResponse extends Exception {
    
    private org.rifidi.edge.epcglobal.alelr.ImplementationException implementationException;

    public ImplementationExceptionResponse() {
        super();
    }
    
    public ImplementationExceptionResponse(String message) {
        super(message);
    }
    
    public ImplementationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImplementationExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ImplementationException implementationException) {
        super(message);
        this.implementationException = implementationException;
    }

    public ImplementationExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ImplementationException implementationException, Throwable cause) {
        super(message, cause);
        this.implementationException = implementationException;
    }

    public org.rifidi.edge.epcglobal.alelr.ImplementationException getFaultInfo() {
        return this.implementationException;
    }
}
