//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.12 at 01:52:04 PM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:epcglobal:ale:xsd:1")
package org.rifidi.edge.epcglobal.alelr;
