
package org.rifidi.edge.epcglobal.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T10:17:43.142-05:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "ReaderLoopException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ReaderLoopExceptionResponse extends Exception {
    
    private org.rifidi.edge.epcglobal.alelr.ReaderLoopException readerLoopException;

    public ReaderLoopExceptionResponse() {
        super();
    }
    
    public ReaderLoopExceptionResponse(String message) {
        super(message);
    }
    
    public ReaderLoopExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ReaderLoopExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ReaderLoopException readerLoopException) {
        super(message);
        this.readerLoopException = readerLoopException;
    }

    public ReaderLoopExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ReaderLoopException readerLoopException, Throwable cause) {
        super(message, cause);
        this.readerLoopException = readerLoopException;
    }

    public org.rifidi.edge.epcglobal.alelr.ReaderLoopException getFaultInfo() {
        return this.readerLoopException;
    }
}
