
package org.rifidi.edge.epcglobal.alelr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T10:17:43.124-05:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "ValidationException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ValidationExceptionResponse extends Exception {
    
    private org.rifidi.edge.epcglobal.alelr.ValidationException validationException;

    public ValidationExceptionResponse() {
        super();
    }
    
    public ValidationExceptionResponse(String message) {
        super(message);
    }
    
    public ValidationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ValidationExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ValidationException validationException) {
        super(message);
        this.validationException = validationException;
    }

    public ValidationExceptionResponse(String message, org.rifidi.edge.epcglobal.alelr.ValidationException validationException, Throwable cause) {
        super(message, cause);
        this.validationException = validationException;
    }

    public org.rifidi.edge.epcglobal.alelr.ValidationException getFaultInfo() {
        return this.validationException;
    }
}
