
package org.rifidi.edge.client.ale.wsdl.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 09 15:04:22 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "NoSuchNameException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class NoSuchNameExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090209150422L;
    
    private org.rifidi.edge.client.ale.wsdl.epcglobal.NoSuchNameException noSuchNameException;

    public NoSuchNameExceptionResponse() {
        super();
    }
    
    public NoSuchNameExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchNameExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchNameExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.epcglobal.NoSuchNameException noSuchNameException) {
        super(message);
        this.noSuchNameException = noSuchNameException;
    }

    public NoSuchNameExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.epcglobal.NoSuchNameException noSuchNameException, Throwable cause) {
        super(message, cause);
        this.noSuchNameException = noSuchNameException;
    }

    public org.rifidi.edge.client.ale.wsdl.epcglobal.NoSuchNameException getFaultInfo() {
        return this.noSuchNameException;
    }
}
