
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.rifidi.edge.server.epcglobal.alelr;

import java.io.File;
import java.util.List;
import java.util.Set;
import java.util.logging.Logger;

import org.rifidi.edge.epcglobal.alelr.ALELRServicePortType;
import org.rifidi.edge.epcglobal.alelr.AddReaders;
import org.rifidi.edge.epcglobal.alelr.Define;
import org.rifidi.edge.epcglobal.alelr.DuplicateNameExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.EmptyParms;
import org.rifidi.edge.epcglobal.alelr.GetLRSpec;
import org.rifidi.edge.epcglobal.alelr.GetPropertyValue;
import org.rifidi.edge.epcglobal.alelr.ImmutableReaderExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.ImplementationExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.InUseExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.NoSuchNameExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.NonCompositeReaderExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.ReaderLoopExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.RemoveReaders;
import org.rifidi.edge.epcglobal.alelr.SecurityExceptionResponse;
import org.rifidi.edge.epcglobal.alelr.SetProperties;
import org.rifidi.edge.epcglobal.alelr.SetReaders;
import org.rifidi.edge.epcglobal.alelr.Undefine;
import org.rifidi.edge.epcglobal.alelr.Update;
import org.rifidi.edge.epcglobal.alelr.ValidationExceptionResponse;
import org.rifidi.edge.notification.TagReadEvent;
import org.rifidi.edge.server.epcglobal.alelr.services.ReaderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-12T10:17:43.148-05:00
 * Generated source version: 3.1.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "ALELRService",
                      portName = "ALELRServicePort",
                      targetNamespace = "urn:epcglobal:alelr:wsdl:1",
                      wsdlLocation = "org/rifidi/edge/alelr/xsd/EPCglobal-ale-1_1-alelr.wsdl",
                      endpointInterface = "org.rifidi.edge.epcglobal.alelr.ALELRServicePortType")
@Service                      
public class AleLR implements ALELRServicePortType {
	
	
	@Autowired
	ReaderService readerService;

    private static final Logger LOG = Logger.getLogger(AleLR.class.getName());
    
    public AleLR(){
    	System.out.println("AleLR() call");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#undefine(org.rifidi.edge.epcglobal.alelr.Undefine  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.UndefineResult undefine(Undefine parms) throws SecurityExceptionResponse , InUseExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ImplementationExceptionResponse    { 
        LOG.info("Executing operation undefine");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.UndefineResult _return = new org.rifidi.edge.epcglobal.alelr.UndefineResult();
            readerService.undefine(parms.getName());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }
    
//    public File EPCglobal-ale-1_1-alelr.xsd(){
//    	
//    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#getLRSpec(org.rifidi.edge.epcglobal.alelr.GetLRSpec  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.LRSpec getLRSpec(GetLRSpec parms) throws SecurityExceptionResponse , ImplementationExceptionResponse , NoSuchNameExceptionResponse    { 
        LOG.info("Executing operation getLRSpec");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.LRSpec _return = null;
            _return = readerService.getLRSpec(parms.getName());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#getStandardVersion(org.rifidi.edge.epcglobal.alelr.EmptyParms  parms )*
     */
    public java.lang.String getStandardVersion(EmptyParms parms) throws ImplementationExceptionResponse    { 
        LOG.info("Executing operation getStandardVersion");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            _return = readerService.getStandardVersion();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#define(org.rifidi.edge.epcglobal.alelr.Define  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.DefineResult define(Define parms) throws SecurityExceptionResponse , ImplementationExceptionResponse , DuplicateNameExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation define alelr");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.DefineResult _return = new org.rifidi.edge.epcglobal.alelr.DefineResult();
            readerService.define(parms.getName(), parms.getSpec());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new DuplicateNameExceptionResponse("DuplicateNameExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#setProperties(org.rifidi.edge.epcglobal.alelr.SetProperties  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.SetPropertiesResult setProperties(SetProperties parms) throws SecurityExceptionResponse , InUseExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ImplementationExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation setProperties");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.SetPropertiesResult _return = new org.rifidi.edge.epcglobal.alelr.SetPropertiesResult();
            readerService.setProperties(parms.getName(), parms.getProperties().getProperty());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#getPropertyValue(org.rifidi.edge.epcglobal.alelr.GetPropertyValue  parms )*
     */
    public java.lang.String getPropertyValue(GetPropertyValue parms) throws SecurityExceptionResponse , ImplementationExceptionResponse , NoSuchNameExceptionResponse    { 
        LOG.info("Executing operation getPropertyValue");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            _return = readerService.getPropertyValue(parms.getName(), parms.getPropertyName());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#removeReaders(org.rifidi.edge.epcglobal.alelr.RemoveReaders  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.RemoveReadersResult removeReaders(RemoveReaders parms) throws SecurityExceptionResponse , NonCompositeReaderExceptionResponse , InUseExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ImplementationExceptionResponse    { 
        LOG.info("Executing operation removeReaders");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.RemoveReadersResult _return = new org.rifidi.edge.epcglobal.alelr.RemoveReadersResult();
            readerService.removeReaders(parms.getName(), parms.getReaders().getReader());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#getVendorVersion(org.rifidi.edge.epcglobal.alelr.EmptyParms  parms )*
     */
    public java.lang.String getVendorVersion(EmptyParms parms) throws ImplementationExceptionResponse    { 
        LOG.info("Executing operation getVendorVersion");
        System.out.println(parms);
        try {
            java.lang.String _return = "";
            _return = readerService.getVendorVersion();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#addReaders(org.rifidi.edge.epcglobal.alelr.AddReaders  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.AddReadersResult addReaders(AddReaders parms) throws SecurityExceptionResponse , NonCompositeReaderExceptionResponse , ReaderLoopExceptionResponse , InUseExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ImplementationExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation addReaders");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.AddReadersResult _return = new org.rifidi.edge.epcglobal.alelr.AddReadersResult();
            readerService.addReaders(parms.getName(), parms.getReaders().getReader());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
        //throw new ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#getLogicalReaderNames(org.rifidi.edge.epcglobal.alelr.EmptyParms  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.ArrayOfString getLogicalReaderNames(EmptyParms parms) throws SecurityExceptionResponse , ImplementationExceptionResponse    { 
        LOG.info("Executing operation getLogicalReaderNames");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.ArrayOfString _return = new org.rifidi.edge.epcglobal.alelr.ArrayOfString();
            List<String> logicalReaderList = readerService.getLogicalReaderNames();
                        
            _return.getString().addAll( logicalReaderList );
            
            return _return;
                        
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#update(org.rifidi.edge.epcglobal.alelr.Update  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.UpdateResult update(Update parms) throws SecurityExceptionResponse , ReaderLoopExceptionResponse , InUseExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ImplementationExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation update");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.UpdateResult _return = new org.rifidi.edge.epcglobal.alelr.UpdateResult();
            readerService.update(parms.getName(), parms.getSpec());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

    /* (non-Javadoc)
     * @see org.rifidi.edge.epcglobal.alelr.ALELRServicePortType#setReaders(org.rifidi.edge.epcglobal.alelr.SetReaders  parms )*
     */
    public org.rifidi.edge.epcglobal.alelr.SetReadersResult setReaders(SetReaders parms) throws SecurityExceptionResponse , NonCompositeReaderExceptionResponse , ReaderLoopExceptionResponse , InUseExceptionResponse , ImmutableReaderExceptionResponse , NoSuchNameExceptionResponse , ImplementationExceptionResponse , ValidationExceptionResponse    { 
        LOG.info("Executing operation setReaders");
        System.out.println(parms);
        try {
            org.rifidi.edge.epcglobal.alelr.SetReadersResult _return = new org.rifidi.edge.epcglobal.alelr.SetReadersResult();
            readerService.setReaders(parms.getName(), parms.getReaders().getReader());
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SecurityExceptionResponse("SecurityExceptionResponse...");
        //throw new NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
        //throw new ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
        //throw new InUseExceptionResponse("InUseExceptionResponse...");
        //throw new ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
        //throw new NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
        //throw new ImplementationExceptionResponse("ImplementationExceptionResponse...");
        //throw new ValidationExceptionResponse("ValidationExceptionResponse...");
    }

}
