
package org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Mar 02 15:28:33 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "ImmutableReaderException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ImmutableReaderExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090302152833L;
    
    private org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImmutableReaderException immutableReaderException;

    public ImmutableReaderExceptionResponse() {
        super();
    }
    
    public ImmutableReaderExceptionResponse(String message) {
        super(message);
    }
    
    public ImmutableReaderExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImmutableReaderExceptionResponse(String message, org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImmutableReaderException immutableReaderException) {
        super(message);
        this.immutableReaderException = immutableReaderException;
    }

    public ImmutableReaderExceptionResponse(String message, org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImmutableReaderException immutableReaderException, Throwable cause) {
        super(message, cause);
        this.immutableReaderException = immutableReaderException;
    }

    public org.rifidi.edge.client.ale.api.wsdl.alelr.epcglobal.ImmutableReaderException getFaultInfo() {
        return this.immutableReaderException;
    }
}
