/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.rifidi.edge.epcglobal.ale.api.lr.ws;

import java.net.MalformedURLException;
import java.net.URL;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 * This class was generated by Apache CXF 2.1.3 Thu Jan 29 11:03:18 EST 2009
 * Generated source version: 2.1.3
 * 
 */

@javax.jws.WebService(serviceName = "ALELRService", portName = "ALELRServicePort", targetNamespace = "urn:epcglobal:alelr:wsdl:1", wsdlLocation = "org/rifidi/edge/epcglobal/ale/api/lr/ws/epcglobal-ale-1_1-alelr.wsdl", endpointInterface = "org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType")
public class ALELRServicePortTypeImpl implements ALELRServicePortType,
		org.rifidi.edge.wsmanagement.WebService {
	/** Logger for this class. */
	private static final Log logger = LogFactory
			.getLog(ALELRServicePortTypeImpl.class);

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#getLRSpec
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.GetLRSpec parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.data.LRSpec getLRSpec(
			GetLRSpec parms) throws SecurityExceptionResponse,
			ImplementationExceptionResponse, NoSuchNameExceptionResponse {
		logger.info("Executing operation getLRSpec");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.data.LRSpec _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @seeorg.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#
	 * getStandardVersion(org.rifidi.edge.epcglobal.ale.api.lr.ws.EmptyParms
	 * parms )
	 */
	public java.lang.String getStandardVersion(EmptyParms parms)
			throws ImplementationExceptionResponse {
		logger.info("Executing operation getStandardVersion");
		System.out.println(parms);
		try {
			java.lang.String _return = "";
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#undefine
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.Undefine parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.UndefineResult undefine(
			Undefine parms) throws SecurityExceptionResponse,
			InUseExceptionResponse, ImplementationExceptionResponse,
			ImmutableReaderExceptionResponse, NoSuchNameExceptionResponse {
		logger.info("Executing operation undefine");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.UndefineResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new InUseExceptionResponse("InUseExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#define(org
	 * .rifidi.edge.epcglobal.ale.api.lr.ws.Define parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.DefineResult define(
			Define parms) throws SecurityExceptionResponse,
			ImplementationExceptionResponse, DuplicateNameExceptionResponse,
			ValidationExceptionResponse {
		logger.info("Executing operation define");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.DefineResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// DuplicateNameExceptionResponse("DuplicateNameExceptionResponse...");
		// throw new
		// ValidationExceptionResponse("ValidationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#setProperties
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.SetProperties parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.SetPropertiesResult setProperties(
			SetProperties parms) throws SecurityExceptionResponse,
			InUseExceptionResponse, ImplementationExceptionResponse,
			ImmutableReaderExceptionResponse, NoSuchNameExceptionResponse,
			ValidationExceptionResponse {
		logger.info("Executing operation setProperties");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.SetPropertiesResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new InUseExceptionResponse("InUseExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
		// throw new
		// ValidationExceptionResponse("ValidationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#removeReaders
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.RemoveReaders parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.RemoveReadersResult removeReaders(
			RemoveReaders parms) throws NonCompositeReaderExceptionResponse,
			SecurityExceptionResponse, InUseExceptionResponse,
			ImplementationExceptionResponse, ImmutableReaderExceptionResponse,
			NoSuchNameExceptionResponse {
		logger.info("Executing operation removeReaders");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.RemoveReadersResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new
		// NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new InUseExceptionResponse("InUseExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#addReaders
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.AddReaders parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.AddReadersResult addReaders(
			AddReaders parms) throws ReaderLoopExceptionResponse,
			NonCompositeReaderExceptionResponse, SecurityExceptionResponse,
			InUseExceptionResponse, ImplementationExceptionResponse,
			ImmutableReaderExceptionResponse, NoSuchNameExceptionResponse,
			ValidationExceptionResponse {
		logger.info("Executing operation addReaders");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.AddReadersResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new
		// ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
		// throw new
		// NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new InUseExceptionResponse("InUseExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
		// throw new
		// ValidationExceptionResponse("ValidationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#update(org
	 * .rifidi.edge.epcglobal.ale.api.lr.ws.Update parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.UpdateResult update(
			Update parms) throws ReaderLoopExceptionResponse,
			SecurityExceptionResponse, InUseExceptionResponse,
			ImplementationExceptionResponse, ImmutableReaderExceptionResponse,
			NoSuchNameExceptionResponse, ValidationExceptionResponse {
		logger.info("Executing operation update");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.UpdateResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new
		// ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new InUseExceptionResponse("InUseExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
		// throw new
		// ValidationExceptionResponse("ValidationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#setReaders
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.SetReaders parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.SetReadersResult setReaders(
			SetReaders parms) throws ReaderLoopExceptionResponse,
			NonCompositeReaderExceptionResponse, SecurityExceptionResponse,
			InUseExceptionResponse, ImplementationExceptionResponse,
			ImmutableReaderExceptionResponse, NoSuchNameExceptionResponse,
			ValidationExceptionResponse {
		logger.info("Executing operation setReaders");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.SetReadersResult _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new
		// ReaderLoopExceptionResponse("ReaderLoopExceptionResponse...");
		// throw new
		// NonCompositeReaderExceptionResponse("NonCompositeReaderExceptionResponse...");
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new InUseExceptionResponse("InUseExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// ImmutableReaderExceptionResponse("ImmutableReaderExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
		// throw new
		// ValidationExceptionResponse("ValidationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#getVendorVersion
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.EmptyParms parms )
	 */
	public java.lang.String getVendorVersion(EmptyParms parms)
			throws ImplementationExceptionResponse {
		logger.info("Executing operation getVendorVersion");
		System.out.println(parms);
		try {
			java.lang.String _return = "";
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @seeorg.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#
	 * getLogicalReaderNames(org.rifidi.edge.epcglobal.ale.api.lr.ws.EmptyParms
	 * parms )
	 */
	public org.rifidi.edge.epcglobal.ale.api.lr.ws.ArrayOfString getLogicalReaderNames(
			EmptyParms parms) throws SecurityExceptionResponse,
			ImplementationExceptionResponse {
		logger.info("Executing operation getLogicalReaderNames");
		System.out.println(parms);
		try {
			org.rifidi.edge.epcglobal.ale.api.lr.ws.ArrayOfString _return = null;
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see
	 * org.rifidi.edge.epcglobal.ale.api.lr.ws.ALELRServicePortType#getPropertyValue
	 * (org.rifidi.edge.epcglobal.ale.api.lr.ws.GetPropertyValue parms )
	 */
	public java.lang.String getPropertyValue(GetPropertyValue parms)
			throws SecurityExceptionResponse, ImplementationExceptionResponse,
			NoSuchNameExceptionResponse {
		logger.info("Executing operation getPropertyValue");
		System.out.println(parms);
		try {
			java.lang.String _return = "";
			return _return;
		} catch (Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new SecurityExceptionResponse("SecurityExceptionResponse...");
		// throw new
		// ImplementationExceptionResponse("ImplementationExceptionResponse...");
		// throw new
		// NoSuchNameExceptionResponse("NoSuchNameExceptionResponse...");
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.rifidi.edge.wsmanagement.WebService#getService()
	 */
	@Override
	public Object getService() {
		return this;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see org.rifidi.edge.wsmanagement.WebService#getUrl()
	 */
	@Override
	public URL getUrl() {
		try {
			return new URL("http://127.0.0.1:8081/lr");
		} catch (MalformedURLException e) {
			logger.fatal("That should never ever happen: " + e);
		}
		return null;
	}

}
