
package org.rifidi.edge.client.ale.wsdl.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 09 15:04:22 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "SecurityException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class SecurityExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090209150422L;
    
    private org.rifidi.edge.client.ale.wsdl.epcglobal.SecurityException securityException;

    public SecurityExceptionResponse() {
        super();
    }
    
    public SecurityExceptionResponse(String message) {
        super(message);
    }
    
    public SecurityExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public SecurityExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.epcglobal.SecurityException securityException) {
        super(message);
        this.securityException = securityException;
    }

    public SecurityExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.epcglobal.SecurityException securityException, Throwable cause) {
        super(message, cause);
        this.securityException = securityException;
    }

    public org.rifidi.edge.client.ale.wsdl.epcglobal.SecurityException getFaultInfo() {
        return this.securityException;
    }
}
