
package org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 09 14:59:11 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "InUseException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class InUseExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090209145911L;
    
    private org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.InUseException inUseException;

    public InUseExceptionResponse() {
        super();
    }
    
    public InUseExceptionResponse(String message) {
        super(message);
    }
    
    public InUseExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public InUseExceptionResponse(String message, org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.InUseException inUseException) {
        super(message);
        this.inUseException = inUseException;
    }

    public InUseExceptionResponse(String message, org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.InUseException inUseException, Throwable cause) {
        super(message, cause);
        this.inUseException = inUseException;
    }

    public org.rifidi.edge.client.ale.logicalreader.wsdl.epcglobal.InUseException getFaultInfo() {
        return this.inUseException;
    }
}
