
package org.rifidi.edge.epcglobal.ale.api.lr.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Jan 29 11:03:18 EST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "ImmutableReaderException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class ImmutableReaderExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090129110318L;
    
    private org.rifidi.edge.epcglobal.ale.api.lr.ws.ImmutableReaderException immutableReaderException;

    public ImmutableReaderExceptionResponse() {
        super();
    }
    
    public ImmutableReaderExceptionResponse(String message) {
        super(message);
    }
    
    public ImmutableReaderExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImmutableReaderExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.lr.ws.ImmutableReaderException immutableReaderException) {
        super(message);
        this.immutableReaderException = immutableReaderException;
    }

    public ImmutableReaderExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.lr.ws.ImmutableReaderException immutableReaderException, Throwable cause) {
        super(message, cause);
        this.immutableReaderException = immutableReaderException;
    }

    public org.rifidi.edge.epcglobal.ale.api.lr.ws.ImmutableReaderException getFaultInfo() {
        return this.immutableReaderException;
    }
}
