
package org.rifidi.edge.epcglobal.ale.api.lr.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Thu Jan 29 11:03:18 EST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "NonCompositeReaderException", targetNamespace = "urn:epcglobal:alelr:wsdl:1")
public class NonCompositeReaderExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090129110318L;
    
    private org.rifidi.edge.epcglobal.ale.api.lr.ws.NonCompositeReaderException nonCompositeReaderException;

    public NonCompositeReaderExceptionResponse() {
        super();
    }
    
    public NonCompositeReaderExceptionResponse(String message) {
        super(message);
    }
    
    public NonCompositeReaderExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NonCompositeReaderExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.lr.ws.NonCompositeReaderException nonCompositeReaderException) {
        super(message);
        this.nonCompositeReaderException = nonCompositeReaderException;
    }

    public NonCompositeReaderExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.lr.ws.NonCompositeReaderException nonCompositeReaderException, Throwable cause) {
        super(message, cause);
        this.nonCompositeReaderException = nonCompositeReaderException;
    }

    public org.rifidi.edge.epcglobal.ale.api.lr.ws.NonCompositeReaderException getFaultInfo() {
        return this.nonCompositeReaderException;
    }
}
