/*
 *  RifidiIllegalOperationException.java
 *
 *  Created:	Jun 27, 2008
 *  Project:	RiFidi Emulator - A Software Simulation Tool for RFID Devices
 *  				http://www.rifidi.org
 *  				http://rifidi.sourceforge.net
 *  Copyright:	Pramari LLC and the Rifidi Project
 *  License:	Lesser GNU Public License (LGPL)
 *  				http://www.opensource.org/licenses/lgpl-license.html
 */
package org.rifidi.edge.core.exception.readerConnection;

import org.rifidi.edge.core.exception.RifidiException;

//TODO Needs class comment header...
public class RifidiIllegalOperationException extends RifidiException {

	/**
	 * Autogenerated SerialVersionID
	 */
	private static final long serialVersionUID = 183170652719764201L;

	public RifidiIllegalOperationException() {
		super();
	}

	public RifidiIllegalOperationException(String message, Throwable cause) {
		super(message, cause);
	}

	public RifidiIllegalOperationException(String message) {
		super(message);
	}

	public RifidiIllegalOperationException(Throwable cause) {
		super(cause);
	}

}
