
package org.rifidi.edge.epcglobal.ale.api.read.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 28 17:30:03 EST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "ImplementationException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class ImplementationExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090128173003L;
    
    private org.rifidi.edge.epcglobal.ale.api.read.ws.ImplementationException implementationException;

    public ImplementationExceptionResponse() {
        super();
    }
    
    public ImplementationExceptionResponse(String message) {
        super(message);
    }
    
    public ImplementationExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public ImplementationExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.read.ws.ImplementationException implementationException) {
        super(message);
        this.implementationException = implementationException;
    }

    public ImplementationExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.read.ws.ImplementationException implementationException, Throwable cause) {
        super(message, cause);
        this.implementationException = implementationException;
    }

    public org.rifidi.edge.epcglobal.ale.api.read.ws.ImplementationException getFaultInfo() {
        return this.implementationException;
    }
}
