
package org.rifidi.edge.epcglobal.ale.api.read.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 28 17:30:03 EST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "InvalidURIException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class InvalidURIExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090128173003L;
    
    private org.rifidi.edge.epcglobal.ale.api.read.ws.InvalidURIException invalidURIException;

    public InvalidURIExceptionResponse() {
        super();
    }
    
    public InvalidURIExceptionResponse(String message) {
        super(message);
    }
    
    public InvalidURIExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidURIExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.read.ws.InvalidURIException invalidURIException) {
        super(message);
        this.invalidURIException = invalidURIException;
    }

    public InvalidURIExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.read.ws.InvalidURIException invalidURIException, Throwable cause) {
        super(message, cause);
        this.invalidURIException = invalidURIException;
    }

    public org.rifidi.edge.epcglobal.ale.api.read.ws.InvalidURIException getFaultInfo() {
        return this.invalidURIException;
    }
}
