
package org.rifidi.edge.epcglobal.ale.api.read.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 28 17:30:03 EST 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "NoSuchSubscriberException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class NoSuchSubscriberExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090128173003L;
    
    private org.rifidi.edge.epcglobal.ale.api.read.ws.NoSuchSubscriberException noSuchSubscriberException;

    public NoSuchSubscriberExceptionResponse() {
        super();
    }
    
    public NoSuchSubscriberExceptionResponse(String message) {
        super(message);
    }
    
    public NoSuchSubscriberExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public NoSuchSubscriberExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.read.ws.NoSuchSubscriberException noSuchSubscriberException) {
        super(message);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public NoSuchSubscriberExceptionResponse(String message, org.rifidi.edge.epcglobal.ale.api.read.ws.NoSuchSubscriberException noSuchSubscriberException, Throwable cause) {
        super(message, cause);
        this.noSuchSubscriberException = noSuchSubscriberException;
    }

    public org.rifidi.edge.epcglobal.ale.api.read.ws.NoSuchSubscriberException getFaultInfo() {
        return this.noSuchSubscriberException;
    }
}
