package org.rifidi.edge.readerplugin.dummy.plugin;

public enum EDummyError {
	CONNECT, DISCONNECT, GET_NEXT_TAGS, SEND_CUSTOM_COMMAND,
	CONNECT_RUNTIME, DISCONNECT_RUNTIME, COMMAND_RUNTIME, COMMAND,
	PROTOCOL_FROM_BYTE, PROTOCOL_FROM_BYTE_RUNTIME,
	PROTOCOL_TO_BYTE, PROTOCOL_TO_BYTE_RUNTIME, RANDOM,
	NONE;
}
