package org.rifidi.edge.readerPlugin.alien.command;

import org.rifidi.edge.core.readerPlugin.commands.ICustomCommandResult;

/**
 * This class represents the resulting output generated by sending a custom
 * command into a reader.
 * 
 * @author Matthew Dean - matt@pramari.com
 */
public class AlienCustomCommandResult implements ICustomCommandResult {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8320598992143116635L;

	/**
	 * 
	 */
	private String result;

	/**
	 * Gets the result for a custom command sent to an Alien reader.
	 * 
	 * @return The custom command result.
	 */
	public String getResult() {
		return result;
	}

	/**
	 * Sets the result for a custom command sent to an Alien reader.
	 * 
	 * @param result
	 */
	public void setResult(String result) {
		this.result = result;
	}

}
