
package org.rifidi.edge.client.ale.wsdl.epcglobal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.1.3
 * Mon Feb 09 15:04:22 CET 2009
 * Generated source version: 2.1.3
 * 
 */

@WebFault(name = "InvalidURIException", targetNamespace = "urn:epcglobal:ale:wsdl:1")
public class InvalidURIExceptionResponse extends Exception {
    public static final long serialVersionUID = 20090209150422L;
    
    private org.rifidi.edge.client.ale.wsdl.epcglobal.InvalidURIException invalidURIException;

    public InvalidURIExceptionResponse() {
        super();
    }
    
    public InvalidURIExceptionResponse(String message) {
        super(message);
    }
    
    public InvalidURIExceptionResponse(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidURIExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.epcglobal.InvalidURIException invalidURIException) {
        super(message);
        this.invalidURIException = invalidURIException;
    }

    public InvalidURIExceptionResponse(String message, org.rifidi.edge.client.ale.wsdl.epcglobal.InvalidURIException invalidURIException, Throwable cause) {
        super(message, cause);
        this.invalidURIException = invalidURIException;
    }

    public org.rifidi.edge.client.ale.wsdl.epcglobal.InvalidURIException getFaultInfo() {
        return this.invalidURIException;
    }
}
