#!/bin/sh

# Change the permissions of the executables
sudo chmod +x /usr/local/sbin/rifidi/rifidiserver
sudo chmod 755 /usr/local/sbin/rifidi/startupscript/rifidiserver

# Start the init.d files
sudo cp /usr/local/sbin/rifidi/startupscript/rifidiserver /etc/init.d
sudo update-rc.d rifidiserver defaults

# Start the rifidiserver
sudo /etc/init.d/rifidiserver start


